{
  imports = [
    ./bar.nix
    ./bootloader.nix
    ./browser.nix
    ./compositor.nix
    ./config/distributed-build.nix
    ./editor.nix
    ./file-manager.nix
    ./file-sync.nix
    ./hardware/amdgpu.nix
    ./hardware/android.nix
    ./hardware/iphone.nix
    ./launcher.nix
    ./packages.nix
    ./programs/git.nix
    ./shell.nix
    ./terminal-emulator.nix
    ./vpn.nix
    ./window-manager.nix
  ];
}
