[
  ./hardware/iphone.nix
  ./module-list.nix
  ./programs/alacritty.nix
  ./programs/bash.nix
  ./programs/betterlockscreen.nix
  ./programs/git.nix
  ./programs/starship.nix
  ./programs/vscode.nix
  ./services/networking/nebula.nix
  ./services/x11/window-managers/bspwm.nix
]
