#!/bin/sh


# ls aliases
alias ll="ls -alF"
alias la="ls -A"
alias l="ls -CF"

# directory aliases
alias ~="cd ~"
alias ..="cd .."
alias -- -="cd -"

# alert alias
# will notify user after previous command has finished
# usage:
#   command; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# temperature alias
alias "temp=watch -n 1 sensors"

# app shortcuts
alias "d=docker"
alias "db=docker build ."
alias "dbt=docker build . --tag"
alias "de=docker exec"
alias "di=docker insepct"
alias "dl=docker logs"
alias "dlf=docker logs -f"
alias "dr=docker run"
alias "drm=docker rm"
alias "drs=docker restart"
alias "ds=docker start"
alias "dt=docker tag"
alias "dp=docker push"
alias "dpl=docker pull"
alias "dps=docker ps"
alias "ds=docker stop"
alias "dsf=docker stop --time 0"
alias "dst=docker stop --time"
alias "dsu=docker service update --force"
alias "py=python"
alias "pyd=pyenv && pipir && pipf && deactivate && rm -rf env"
alias "pyenv=pip install virtualenv && py -m virtualenv env && source env/bin/activate"
alias "pym=python -m"
alias "o=xdg-open"
alias "open=xdg-open"
alias "g=git"
alias "gb=git branch"
alias "gbd=git branch -d"
alias "gbD=git branch -D"
alias "gbm=git branch -m"
alias "gca=git commit --amend"
alias "gch=git checkout"
alias "gcl=git clone"
alias "gd=git diff"
alias "gf=git fetch"
alias "gi=git init"
alias "gl=git log --graph --oneline --decorate"
alias "glf=git log --pretty=fuller"
alias "glo=git log --pretty=oneline"
alias "gm=git merge --no-ff"
alias "gp=git pull; git push"
alias "gpl=git pull"
alias "gps=git push"
alias "gpsf=git push --force"
alias "gr=git remote"
alias "grb=git rebase"
alias "grp=git remote prune"
alias "grpo=git remote prune origin"
alias "grs=git reset --hard"
alias "gs=git status"
alias "gst=git stash"
alias "gstp=git stash pop"
alias "gu=git reset --soft HEAD^"
alias "wifi-scan=nmcli dev wifi list --rescan yes"

# jekyll aliases
alias "jks=bundle exec jekyll serve --livereload"
alias "jkb=bundle exec jekyll build"

# pip aliases
alias "pipf=pip freeze > requirements.txt"
alias "pipi=pip install"
alias "pipir=pip install -r requirements.txt"
alias "pipih=pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org"
alias "pipl=pip list"
alias "pipu=pip uninstall"
