[package]
name = "timetable"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.0"
fuzzy-matcher = "0.3.7"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.79"
tabled = { version = "0.5.0", features = ["color"] }

[features]
