[package]
name = "timetable"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.24.0"
fuzzy-matcher = "0.3.7"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
tabled = { version = "0.6.1", features = ["color"] }

[features]
