[tool.poetry]
name = "timetable"
version = "0.1.0"
description = "Easily check your timetable from the terminal"
authors = ["Joel <joel@joel.tokyo>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
fuzzywuzzy = "^0.18.0"
rich = "^11.0.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
timetable = "timetable:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
