name: "ci"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Print nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - name: Check formatting with nixpkgs-fmt
        run: nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt --check ."
      - name: Check for common mistakes with nix-linter
        run: nix-shell -p nix-linter --run "nix-linter -r ."
      - name: Check flake evaluates
        run: nix flake check
