name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get install shellcheck
      - name: lint with shellcheck
        run: |
          find . -exec [ -f {} ] \; \
            -exec [ ! -L {} ] \; \
            -exec grep -q "#\!/usr/bin/env bash" {} \; \
            -exec shellcheck -e SC1091 {} \;
  test_laptop:
    name: "test: laptop"
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./install.sh laptop
  test_server:
    name: "test: server"
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./install.sh laptop
  test_devcontainer:
    name: "test: devcontainer"
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/vscode/devcontainers/python:0-3.9
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./install.sh devcontainer
  test_certificate_repository:
    name: "test: certificate: repository"
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./install.sh laptop
  test_certificate_curl:
    name: "test: certificate: curl"
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -ks "https://raw.githubusercontent.com/jyooru/dotfiles/main/install.sh" | bash -s certificate
