name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get install shellcheck
      - name: lint with shellcheck
        run: |
          readarray -d '' files < <(find . \
            -not -path "./.git/*" \
            -exec [ -f {} ] \; \
            -exec [ ! -L {} ] \; \
            -exec grep -q "#\!/usr/bin/env bash" {} \; \
            -print0)
          success=true
          for file in "${files[@]}"; do
            shellcheck -e SC1091 "$file" || success=false
          done
          if [ "$success" = false ]; then
            exit 1
          fi
  test:
    strategy:
      matrix:
        container: [ubuntu]
        run:
          - "./install.sh laptop"
          - "./install.sh server"
          - "./install.sh devcontainer"
          - "./install.sh certificate"
          - "curl -ks 'https://raw.githubusercontent.com/jyooru/dotfiles/main/install.sh' | bash -s certificate"
    name: "test: ${{ matrix.container }}: ${{ matrix.run }}"
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.run }}
