name: test

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get install shellcheck
      - name: lint with shellcheck
        # TODO: find a better way to get shell files
        run: |
          shellcheck -s bash -e SC1091 \
            laptop/.aliases laptop/.bashrc laptop/.exports laptop/.functions laptop/.profile laptop/vscode/extensions.sh \
            install.sh
  install:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: test install
        run: |
          ./install.sh laptop
