name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get install shellcheck
      - name: lint with shellcheck
        run: |
          shellcheck .aliases .bashrc .exports .functions .profile install.sh
